### ISSUE TITLE
Latest drafts

### ISSUE THREAD

**Issue by brettz9** [awwright/json-metaschema#2]
Could you kindly update with the latest drafts?

**Comment by awwright** [comment]
@brettz9 Done

**Comment by brettz9** [comment]
Thanks! FYI, the repo hasn't apparently been updated correspondingly, but I do see the version has been bumped at npm...

**Comment by awwright** [comment]
Oh dear, I think I forgot to push. Look again!

**Comment by brettz9** [comment]
Yup, all good...Thanks a lot!

**Comment by brettz9** [comment]
Oh, and for the record, was there a draft-05 version? I don't need it, but just mentioning in case helpful for your own archiving purposes...

**Comment by awwright** [comment]
@brettz9 There is not. The iteration of the spec we sometimes referred to as draft-05 was only a revision to the specification and used the same meta-schema.
